Play travis
Otus-DevOps-2021-05/Lookus84_infra pull request #2
Opened 2021-07-13 13:19 UTC by Lookus84

Переделал ДЗ. Теперь в нужном репозитории.

2021-07-13 13:52 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз, оставил комментарий к файлу, дз возвращаю на доработку.

2021-07-13 13:52 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот сюда смотрим внимательно =)

2021-07-16 12:04 UTC, Lookus84 commented
исправил тест. Видимо не заметил в домашнем задании, что нужно скорректировать этот тест. Прошу прощения)

2021-07-16 16:11 UTC, mrgreyves commented
Да лаааадна, мелочи =)

2021-07-16 16:11 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-07-19 12:33 UTC, merged