Cloud testapp
Otus-DevOps-2021-05/Lookus84_infra pull request #4
Opened 2021-07-16 17:44 UTC by Lookus84

# Выполнено ДЗ №4. 

- [ ] Перенес файлы *.ovpn и setupvpn.sh , созданные в прошлом ДЗ в директорию VPN
- [ ] Установил ruby используя install_ruby.sh.
- [ ] Установил mongodb используя install_mongodb.sh
- [ ] Установил приложение reddit используя deploy.sh
- [ ] Доп. задание: создал скрипт и yaml для автоматического создания и установки приложения. Данные автоматически созданного хоста(для проверки приложения)

testapp_IP = 84.252.133.140
testapp_port = 9292

Положил все скрипты в каталог cloud-testapp

2021-07-16 18:11 UTC, Lookus84 commented
Добрый день. просьба объяснить ошибки в workflow, поправил какие понял.  Остались не понятные)

2021-07-18 13:22 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил небольшой комментарий, дз возращаю на доработку.

2021-07-18 13:22 UTC, mrgreyves commented on README.md
> +		testapp_IP=84.252.133.140
нужно поправить строки с указанием адреса и порта

2021-07-19 09:42 UTC, Lookus84 commented on README.md
> +		testapp_IP=84.252.133.140
поправил.

2021-07-20 11:37 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. С монгой такое иногда бывает, дз принимаю!=)

2021-07-20 12:52 UTC, merged